#!/bin/bash
################################################################################
# exporter.sh - LSCWP Profile Export for wp-admin Import (export-profile)
################################################################################
# Generates a settings file in LSCWP's NATIVE import format, verified against
# plugin 7.8.1 source (src/import.cls.php):
#   - file extension MUST be .data (the admin upload rejects anything else)
#   - v4+ format: one json_encode([key, value]) pair per line, blank-line
#     separated, FIRST line must start with ["_version",
#   - values are stored as strings (matches data/const.default.json types)
#   - import is PARTIAL: only the keys present are updated
#
# No-SSH delivery: the client imports the file via wp-admin >
# LiteSpeed Cache > Toolbox > Import / Export > Import Settings.
#
# Object-cache keys are EXCLUDED by default — importing object=0 on a site
# that already runs Redis would silently disable it. Opt in with
# --redis-host/--redis-port when you know the site's Redis endpoint.
################################################################################

LSCWP_EXPORT_VERSION="7.8.1"

# _xp_emit <key> <value> — one v4+ import line (JSON string value)
_xp_emit() {
    local key="$1" value="$2"
    # Values are simple option strings (alnum . / : _ -) — escape " and \ anyway
    value=$(printf '%s' "$value" | sed 's/\\/\\\\/g; s/"/\\"/g')
    printf '["%s","%s"]\n\n' "$key" "$value"
}

# run_export_profile <profile> <out-file>
# Honors: PROFILE (resolved), LSO_EXPORT_REDIS_HOST/PORT, LSO_EXPORT_ESI=1
run_export_profile() {
    local profile="${1:-wordpress}"
    local out="${2:-}"

    case "$profile" in
        auto) profile="wordpress" ;;  # no-SSH: no server to detect Woo on; pick explicitly
        woocommerce|wordpress|generic) ;;
        *) log_error "Unknown profile: $profile"; exit 1 ;;
    esac

    [ -z "$out" ] && out="./lscwp-profile-${profile}.data"
    case "$out" in
        *.data) ;;
        *) log_warn "LSCWP admin only accepts *.data files — renaming"; out="${out}.data" ;;
    esac

    local template="${TEMPLATE_DIR}/lscwp/profile-${profile}.txt"
    if [ ! -f "$template" ]; then
        log_error "Profile template not found: $template"
        exit 1
    fi

    # Placeholder values for the no-SSH context
    local object=0 obj_host=localhost obj_port=6379
    if [ -n "${LSO_EXPORT_REDIS_HOST:-}" ]; then
        object=1
        obj_host="$LSO_EXPORT_REDIS_HOST"
        obj_port="${LSO_EXPORT_REDIS_PORT:-6379}"
    fi
    local esi="${LSO_EXPORT_ESI:-0}"
    local cache_priv=0
    [ "$esi" = "1" ] && cache_priv=1

    local rendered
    rendered=$(secure_mktemp "${TMPDIR:-/tmp}/lso-export.XXXXXX") || exit 1
    template_render "$template" \
        "OBJECT=${object}" \
        "OBJECT_HOST=${obj_host}" \
        "OBJECT_PORT=${obj_port}" \
        "ESI=${esi}" \
        "CACHE_PRIV=${cache_priv}" \
        "SITEMAP=" > "$rendered"

    # Build the .data payload
    {
        printf '["_version","%s"]\n\n' "$LSCWP_EXPORT_VERSION"
        local line key value
        while IFS= read -r line; do
            case "$line" in
                ''|'#'*) continue ;;
            esac
            key=$(echo "${line%%=*}" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')
            value=$(echo "${line#*=}" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')
            [ -z "$key" ] && continue

            # Object-cache wiring only when explicitly requested
            if [ "$object" = "0" ]; then
                case "$key" in
                    object|object-*) continue ;;
                esac
            fi

            _xp_emit "$key" "$value"
        done < "$rendered"
    } > "$out"
    rm -f "$rendered"

    log_success "Exported: $out ($(grep -c '^\[' "$out") settings, profile: ${profile})"

    # Companion README with import + verification steps
    local readme="${out%.data}.README.md"
    cat > "$readme" <<EOF
# Importing the '${profile}' LiteSpeed Cache profile

Generated by litespeed-optimizer ${VERSION:-} for **${profile}** sites
(no SSH needed — everything happens in wp-admin).

## Import steps

1. wp-admin > **LiteSpeed Cache > Toolbox > Import / Export**
2. Under **Import Settings**, choose \`$(basename "$out")\` and click Import.
3. wp-admin > **LiteSpeed Cache > Toolbox > Purge > Purge All**.

## Verify afterwards (from any terminal/browser devtools)

- Load any public page twice; the second response must contain
  \`x-litespeed-cache: hit\`.
$([ "$profile" = "woocommerce" ] && cat <<'WOOEOF'
- Load /cart/ — it must NOT show `x-litespeed-cache: hit` (carts are never cached).
- Add a product to the cart in one browser; open the cart in a private window —
  it must be empty there.
WOOEOF
)
- Or run a full remote audit:
  \`litespeed-optimizer analyze --remote https://your-site.example\`

## What this profile intentionally leaves OFF (do not "fix")

- **CSS/JS Combine, UCSS, JS Defer/Delay** — these regularly break add-to-cart
  buttons and payment gateways. Enable one at a time only with full checkout
  testing.
- **Guest Optimization** — causes UCSS file explosion and breaks
  geo/currency-dependent content (Guest *Mode* stays on; that one is safe).
- **Crawler role simulation** — unnecessary attack surface (CVE-2024-28000 class).
$([ "$object" = "0" ] && cat <<'OBJEOF'
- **Object cache settings** — excluded from this file so an existing
  Redis/Memcached setup is not disturbed. Configure manually under
  LiteSpeed Cache > Cache > Object if your host provides Redis
  (set Default Object Lifetime to 600+ for WooCommerce).
OBJEOF
)

Profile reference: https://github.com/MarcinDudekDev/litespeed-optimizer
EOF
    log_info "Instructions: $readme"
}
