; Generated by litespeed-optimizer — OPcache tuning (tier @TIER@)
; Rollback: litespeed-optimizer rollback <timestamp>
opcache.enable=1
opcache.enable_cli=0
opcache.memory_consumption=@MEMORY_MB@
opcache.interned_strings_buffer=@INTERNED_MB@
opcache.max_accelerated_files=@MAX_FILES@
opcache.validate_timestamps=1
opcache.revalidate_freq=60
opcache.save_comments=1
opcache.jit=off
opcache.jit_buffer_size=0
